# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-2019

steps:
- task: PowerShell@2
  env:
    VERACODE_API_KEY_ID: $(VERACODE_ID)
    VERACODE_API_KEY_SECRET: $(VERACODE_SECRET)
  inputs:
    targetType: 'inline'
    script: |
      $env:Path += ";C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
      Set-ExecutionPolicy AllSigned -Scope Process -Force
      $ProgressPreference = "silentlyContinue"; iex ((New-Object System.Net.WebClient).DownloadString('https://tools.veracode.com/veracode-cli/install.ps1'))
      
      veracode package -das . --output verascan
      veracode static scan verascan\veracode-auto-pack-TestDotNet-dotnet.zip